### ISSUE TITLE
koreanspicygarlic - NFT owner can drain the contract

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-radicalxchange-judging#100]
koreanspicygarlic

high

# NFT owner can drain the contract

## Summary
The owner of the NFT being auctioned can steal all ETH from the contract 

## Vulnerability Detail
If the owner of the NFT decides to place a bid on its auction, they don't have to put collateral for the bidAmount, but only for the fee.
```solidity
        if (IStewardLicense(address(this)).exists(tokenId)) {
            currentBidder = IStewardLicense(address(this)).ownerOf(tokenId);
        } else {
            currentBidder = l.initialBidder;
        }

        if (bidder == currentBidder) {
            // If current bidder, collateral is entire fee amount
            feeAmount = totalCollateralAmount;
```

While this may not seem a problem at first glance, it becomes a problem if the ownership of the NFT changes mid-auction. When closing the auction, it checks whether the winner is the current NFT owner, and not the historic value at the time the bid was placed 

```solidity
        } else if (
            l.highestBids[tokenId][currentAuctionRound].bidder != oldBidder
        ) {
            // Transfer bid to previous bidder's collateral
            l.availableCollateral[oldBidder] += l
            .highestBids[tokenId][currentAuctionRound].bidAmount;
            l.highestBids[tokenId][currentAuctionRound].collateralAmount = 0;
            l
            .bids[tokenId][currentAuctionRound][
                l.highestBids[tokenId][currentAuctionRound].bidder
            ].collateralAmount = 0;
```

This can be combined in the following way to drain the contract

1. Owner places bid for the whole ETH balance of the contract. They have to put collateral simply the fee for it.
2. Owner transfers ownership to 2nd wallet
3. Auction ends and closeAuction is invoked. 
4. New Owner's wallet available collateral is increased by bidAmount, which equals to the whole ETH balance of the contract
5. Owner can now withdraw all funds

## Impact
Theft of funds

## Code Snippet
https://github.com/sherlock-audit/2024-02-radicalxchange/blob/main/pco-art/contracts/auction/EnglishPeriodicAuctionInternal.sol#L496C1-L506C36

## Tool used

Manual Review

## Recommendation
change the logic on closeAuction 

Duplicate of #51

**Comment by spacegliderrrr** [comment]
Escalate 

(on behalf of Watson) Valid high. Not a dup of #51

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> (on behalf of Watson) Valid high. Not a dup of #51

You've deleted an escalation for this issue.
