### ISSUE TITLE
koreanspicygarlic - ETH might be burned if bidder becomes owner prior to end of auction

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-radicalxchange-judging#102]
koreanspicygarlic

high

# ETH might be burned if bidder becomes owner prior to end of auction

## Summary
Users may accidentally burn their funds

## Vulnerability Detail
Consider the following scenario: 

1. User A owns the NFT and it goes on auction
2. User B bids 1 ETH for the NFT
3. There's plenty of time until the end of the auction. User A decides they're fine with 1 ETH price and sell the NFT on secondary market for 1 ETH in order to get the funds now.
4. User B is now the owner of the NFT and the highest bidder. They expect if they remain the highest bidder to receive back their bid.
5. However, auction ends and user B wins it, but their funds get burned instead of returned to them due to the following code: 

```solidity
        } else {
            l.highestBids[tokenId][currentAuctionRound].collateralAmount = 0;
            l
            .bids[tokenId][currentAuctionRound][oldBidder].collateralAmount = 0;
        }
```

## Impact
Loss of funds

## Code Snippet
https://github.com/sherlock-audit/2024-02-radicalxchange/blob/main/pco-art/contracts/auction/EnglishPeriodicAuctionInternal.sol#L507

## Tool used

Manual Review

## Recommendation
fix the logic in closeAuction

**Comment by spacegliderrrr** [comment]
Escalate

(on behalf of Watson) Valid issue, clear loss of funds.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> (on behalf of Watson) Valid issue, clear loss of funds.

You've deleted an escalation for this issue.
