### ISSUE TITLE
jah - wrong calculation in englishperiodicautioninternal

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-radicalxchange-judging#116]
jah

high

# wrong calculation in englishperiodicautioninternal

## Summary
a  user cant bid twice on a single round due to a calculation error in the function **EnglishPeriodicAuctionFacet._placebid**  is 
## Vulnerability Detail
In the function **EnglishPeriodicAuctionFacet._placebid**  the fee amount is calculated   by subtracting **totalCollateralAmount - bidAmount**   but the thing  this equation only work when bidding for the first time because if we are bedding for  a second time ` totalCollateralAmount - bidAmount   ` will give us our previous  **bid.collateralAmount  +  our current fee** so   the require fucntion will revert `require(
            _checkBidAmount(bidAmount, feeAmount),
            'EnglishPeriodicAuction: Incorrect bid amount'
        );`
## Impact
a user can't place bid twice 
## Code Snippet
https://github.com/sherlock-audit/2024-02-radicalxchange/blob/main/pco-art/contracts/auction/EnglishPeriodicAuctionInternal.sol#L338
## Tool used
Manual Review
## Recommendation
only use that equation when the bid is its first  

Duplicate of #14

**Comment by Demelew** [comment]
Escalate 
this is not a dup of #14 ,   this  issues talk about a bug where a user can't bid on a single auction twice due to incorrect calculation where as the #14  talk about  a missing check on **_cancelAllBids** function

**Comment by sherlock-admin2** [comment]
> Escalate 
> this is not a dup of #14    this  issues talk about a bug where a user can't bid on a single auction twice due to incorrect calculation where as the #14  talk about  a missing check on **_cancelAllBids** function

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
On first glance it appeared invalid to me let me know your thoughts @gravenp @Czar102 @zzykxx ?

**Comment by gravenp** [comment]
Agree that this is invalid—incorrect reading of the code/logic.

**Comment by Czar102** [comment]
@Hash01011122 can you elaborate on why is this report invalid? So that the author will have the ability to defend their issue.

**Comment by ghost** [comment]
The logic in itself is incorrect, how will the second bid be differently accounted for `bidAmount` and `feeAmount`. As the equation `totalCollateralAmount-bidAmount` will be cached for second bid and write the latest `bidAmount` and `feeAmount` in the require statement. Watson doesn't even specify any proper attack vector to make sense in his report and didn't even respond after escalating whether he is pointing on `totalCollateralAmount-bidAmount` not being cached or `bidAmount` and `feeAmount` being the same as first one. Even we consider any of the two, then none of them is going to happen in real scenario.

**Comment by Czar102** [comment]
@Demelew any response? If not, I will reject the escalation and leave the issue as is.

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #14

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [demelew](https://github.com/sherlock-audit/2024-02-radicalxchange-judging/issues/116/#issuecomment-2027743694): rejected
