### ISSUE TITLE
jah - pervious owner cant bid  because of the fee calculation amount in EnglishPeriodicAuctionInternal._placeBid

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-radicalxchange-judging#126]
jah

high

# pervious owner cant bid  because of the fee calculation amount in EnglishPeriodicAuctionInternal._placeBid

## Summary
 the function ** EnglishPeriodicAuctionInternal._placeBid**  line  327 if the previous owner is the bidder it will  add the totalCollateralAmount in to the fee amount so when the require function on line  338 which check the transfer fee amount the reauire function will revert 
## Vulnerability Detail
the function ** EnglishPeriodicAuctionInternal._placeBid**  line  327 if the previous owner is the bidder it will  add the totalCollateralAmount in to the fee amount so when the require function on line  338 which check the transfer fee amount the reauire function will revert 
## Impact
 the previous owner cant bid again on this round 
## Code Snippet
https://github.com/sherlock-audit/2024-02-radicalxchange/blob/main/pco-art/contracts/auction/EnglishPeriodicAuctionInternal.sol#L327C13-L327C22
## Tool used

Manual Review

## Recommendation
dont add into the feeamount

**Comment by Demelew** [comment]
Escalate
the pervious owner might want not to lose this tokenid or might want to increase the bid so he might want to bid on this nft again but due to line 327 adding              feeAmount = totalCollateralAmount;  which leads to line 338  **_checkBidAmount** revert

**Comment by sherlock-admin2** [comment]
> Escalate
> the pervious owner might want not to lose this tokenid or might want to increase the bid so he might want to bid on this nft again but due to line 327 adding              feeAmount = totalCollateralAmount;  which leads to line 338  **_checkBidAmount** revert 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
Hey buddy honestly look at the report and answer the following questions:
Is there any valid root cause mentioned in the report?
Is your report comprehensible enough??
 
 Moreover, this was invalidated due to the fact that this is design choice and functions work as intended. On second thoughts this appear to be duplicate of #92 but that issue is of low severity

**Comment by Czar102** [comment]
@Demelew any response? If not, planning to reject the escalation and leave the issue as is.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [demelew](https://github.com/sherlock-audit/2024-02-radicalxchange-judging/issues/126/#issuecomment-2027752153): rejected
