### ISSUE TITLE
devAnas - Malicious Users Can Prolong Auction Duration, Preventing closeAuction Function from Executing

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-radicalxchange-judging#35]
devAnas

medium

# Malicious Users Can Prolong Auction Duration, Preventing closeAuction Function from Executing

medium

## Summary
When place a bid, any user can prolong the audit duration makes auction duration too long,

## Vulnerability Detail
https://github.com/sherlock-audit/2024-02-radicalxchange/blob/main/pco-art/contracts/auction/EnglishPeriodicAuctionInternal.sol#L286-L373

Attack Scenario:
malcious user: Alice 
Normal User: Bob

Bob place a bid and become the highest bidder and extend the auction duration.
Now, Alice place a bid greater than the Bob and become highest bidder and extend the auction, what Alice can do is place bid greater than the highest bidder and withdraw his collateral just after the placing the bid,
Alice continously can place bids and withdraw his collateral in a loop without losing any money and since it is not deployed on Ethereum, making gas so cheap.

So every time place a bid `currentAuctionLength` extend and this also increase the auction end time, makes unable to close auction.
## Impact
Highest bidder can't get his tokenId due time

## Code Snippet
```javascript
        uint256 auctionEndTime = _auctionEndTime(tokenId);

        // slither-disable-start timestamp
        if (
            auctionEndTime >= block.timestamp &&
            auctionEndTime - block.timestamp <
            _bidExtensionWindowLengthSeconds()
        ) {
            uint256 auctionLengthSeconds;
            if (l.currentAuctionLength[tokenId] == 0) {
                auctionLengthSeconds = _auctionLengthSeconds();
            } else {
                auctionLengthSeconds = l.currentAuctionLength[tokenId];
            }
            // @audit mapping extend everytime when placing bid
            l.currentAuctionLength[tokenId] =
                auctionLengthSeconds +
                _bidExtensionSeconds();
        }
```
## Tool used

Manual Review

## Recommendation
Allow only the admin to prolong the duration of an auction

**Comment by gravenp** [comment]
Auction extension is working as designed.
